# Generated by Django 3.2 on 2021-05-13 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skateteam', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teamcat',
            options={'verbose_name_plural': 'Teamcat'},
        ),
    ]
